// This file is generated by Velite

import type __vc from '../../velite.config.ts'

type Collections = typeof __vc.collections

export type Chapter = Collections['chapters']['schema']['_output']
export declare const chapters: Chapter[]

export type Entry = Collections['entries']['schema']['_output']
export declare const entries: Entry[]

export type Piece = Collections['pieces']['schema']['_output']
export declare const pieces: Piece[]
